---
- hosts: all
  tasks:
    - name: Install Terraform
      ansible.builtin.script: scripts/Install-Terraform.sh
    - name: Install the Azure CLI
      ansible.builtin.script: scripts/Install-AzureCli.sh
    - name: Install Packer
      ansible.builtin.script: scripts/Install-Packer.sh
    - name: Install Docker
      ansible.builtin.script: scripts/Install-Docker.sh
    - name: Install Kubectl
      ansible.builtin.script: scripts/Install-Kubectl.sh
    - name: Install Helm
      ansible.builtin.script: scripts/Install-Helm.sh
    - name: Set BASH Aliases
      ansible.builtin.script: scripts/Set-BashAliases.sh